{
    "source file": "training_utils_test.py",
    "line number": "309",
    "func name": "cause_error",
    "func arg": "(f)",
    "comments": ""
}