{
    "source file": "test_utils_reqser.py",
    "line number": "147",
    "func name": "private_handle_error",
    "func arg": "(failure)",
    "comments": ""
}